/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quickmathv2.Interface;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.*;
import javax.sound.sampled.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
/**
 *
 * @author Lenovo
 */
public class MainPage extends javax.swing.JFrame {
private boolean isPlaying = false;
private Clip clip;


    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        Name.uName1=null;
        // Use the singleton MusicPlayer to avoid overlapping playback
        MusicPlayer player = MusicPlayer.getInstance();
        if (!player.isPlaying()) {
            player.playMusic();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        learningmode = new javax.swing.JPanel();
        lpanel = new javax.swing.JLabel();
        rankmode = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        exammode = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        iconslash = new javax.swing.JLabel();
        iconplus = new javax.swing.JLabel();
        iconmulti = new javax.swing.JLabel();
        iconranking = new javax.swing.JLabel();
        rankingpanel = new javax.swing.JPanel();
        ranking = new javax.swing.JLabel();
        aboutpanel = new javax.swing.JPanel();
        aboutus = new javax.swing.JLabel();
        musicpanel = new javax.swing.JPanel();
        music = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("MV Boli", 0, 80)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("QUICK MATHS");

        learningmode.setBackground(new java.awt.Color(204, 204, 255));
        learningmode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                learningmodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                learningmodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                learningmodeMouseExited(evt);
            }
        });

        lpanel.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        lpanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpanel.setText("Learning MODE");
        lpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lpanelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout learningmodeLayout = new javax.swing.GroupLayout(learningmode);
        learningmode.setLayout(learningmodeLayout);
        learningmodeLayout.setHorizontalGroup(
            learningmodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learningmodeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lpanel)
                .addGap(68, 68, 68))
        );
        learningmodeLayout.setVerticalGroup(
            learningmodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, learningmodeLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lpanel)
                .addGap(14, 14, 14))
        );

        rankmode.setBackground(new java.awt.Color(255, 204, 204));
        rankmode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankmodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rankmodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rankmodeMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Rank MODE");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout rankmodeLayout = new javax.swing.GroupLayout(rankmode);
        rankmode.setLayout(rankmodeLayout);
        rankmodeLayout.setHorizontalGroup(
            rankmodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankmodeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        rankmodeLayout.setVerticalGroup(
            rankmodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankmodeLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        exammode.setBackground(new java.awt.Color(255, 255, 204));
        exammode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exammodeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exammodeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exammodeMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Exam MODE");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exammodeLayout = new javax.swing.GroupLayout(exammode);
        exammode.setLayout(exammodeLayout);
        exammodeLayout.setHorizontalGroup(
            exammodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exammodeLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        exammodeLayout.setVerticalGroup(
            exammodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, exammodeLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(14, 14, 14))
        );

        iconslash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/Capture-removebg-preview (1) (1) (1).png"))); // NOI18N

        iconplus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/depositphotos_225571144-stock-illustration-cartoon-doodle-symbol-removebg-preview (1).png"))); // NOI18N

        iconmulti.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/depositphotos_225554910-stock-illustration-cartoon-doodle-multiplication-symbol-removebg-preview (1).png"))); // NOI18N

        iconranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/southeast-removebg-preview (1).png"))); // NOI18N

        rankingpanel.setBackground(new java.awt.Color(204, 255, 255));
        rankingpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingpanelMouseClicked(evt);
            }
        });

        ranking.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/leaderboard_17991170 (1).png"))); // NOI18N
        ranking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankingMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rankingpanelLayout = new javax.swing.GroupLayout(rankingpanel);
        rankingpanel.setLayout(rankingpanelLayout);
        rankingpanelLayout.setHorizontalGroup(
            rankingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankingpanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(ranking, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        rankingpanelLayout.setVerticalGroup(
            rankingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ranking, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        aboutpanel.setBackground(new java.awt.Color(204, 255, 255));
        aboutpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutpanelMouseClicked(evt);
            }
        });

        aboutus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/user_3161848 (1) (2).png"))); // NOI18N
        aboutus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout aboutpanelLayout = new javax.swing.GroupLayout(aboutpanel);
        aboutpanel.setLayout(aboutpanelLayout);
        aboutpanelLayout.setHorizontalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aboutpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aboutus)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        aboutpanelLayout.setVerticalGroup(
            aboutpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutpanelLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(aboutus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        musicpanel.setBackground(new java.awt.Color(204, 255, 255));
        musicpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicpanelMouseClicked(evt);
            }
        });

        music.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/music_556829 (2).png"))); // NOI18N
        music.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                musicMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout musicpanelLayout = new javax.swing.GroupLayout(musicpanel);
        musicpanel.setLayout(musicpanelLayout);
        musicpanelLayout.setHorizontalGroup(
            musicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musicpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(music)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musicpanelLayout.setVerticalGroup(
            musicpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(music, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ranking");

        jLabel4.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Music");

        jLabel5.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("About Us");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconranking, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aboutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(iconslash, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(iconplus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(learningmode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(exammode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rankmode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(59, 59, 59)
                                    .addComponent(iconmulti)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rankingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(musicpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(musicpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rankingpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(iconplus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(learningmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(aboutpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconranking, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconslash, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(iconmulti, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(exammode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(rankmode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learningmodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learningmodeMouseEntered
        // TODO add your handling code here:
        learningmode.setBackground(Color.decode("#9370DB"));
    }//GEN-LAST:event_learningmodeMouseEntered

    private void learningmodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learningmodeMouseExited
        // TODO add your handling code here:
        learningmode.setBackground(Color.decode("#CCCCFF"));
    }//GEN-LAST:event_learningmodeMouseExited

    private void exammodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exammodeMouseExited
        // TODO add your handling code here:
        exammode.setBackground(Color.decode("#FFFFCC"));
    }//GEN-LAST:event_exammodeMouseExited

    private void exammodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exammodeMouseEntered
        // TODO add your handling code here:
        exammode.setBackground(Color.decode("#EEE8AA"));
    }//GEN-LAST:event_exammodeMouseEntered

    private void rankmodeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankmodeMouseEntered
        // TODO add your handling code here:
        rankmode.setBackground(Color.decode("#DB7093"));
    }//GEN-LAST:event_rankmodeMouseEntered

    private void rankmodeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankmodeMouseExited
        // TODO add your handling code here:
        rankmode.setBackground(Color.decode("#FFCCCC"));
    }//GEN-LAST:event_rankmodeMouseExited

    private void aboutpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutpanelMouseClicked
        // TODO add your handling code here:
        AboutUs jf1 = new AboutUs();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_aboutpanelMouseClicked

    private void rankingpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingpanelMouseClicked
        // TODO add your handling code here:
        test2 jf1 = new test2();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_rankingpanelMouseClicked

    private void musicpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicpanelMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_musicpanelMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel1MouseClicked

    private void musicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musicMouseClicked
// Load the play and stop icons once
ImageIcon playIcon = new ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/music_556829 (2).png"));
ImageIcon stopIcon = new ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/music_556829__2_-removebg-preview.png"));

// Toggle music playback and icon based on the current state
MusicPlayer player = MusicPlayer.getInstance();

player.playbuttonMusic();

if (player.isPlaying()) {
    music.setIcon(stopIcon);  // Switch to the stop icon
    player.stopMusic();       // Stop the music
} else {
    music.setIcon(playIcon);  // Switch to the play icon
    player.playMusic();       // Start the music
}
    }//GEN-LAST:event_musicMouseClicked

    private void learningmodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_learningmodeMouseClicked
        // TODO add your handling code here:
        LearningMode jf1 = new LearningMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_learningmodeMouseClicked

    private void exammodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exammodeMouseClicked
        // TODO add your handling code here:
        ExamMode jf1 = new ExamMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_exammodeMouseClicked

    private void rankmodeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankmodeMouseClicked
        // TODO add your handling code here:
        RankMode jf1 = new RankMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_rankmodeMouseClicked

    private void rankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankingMouseClicked
        // TODO add your handling code here:
        test2 jf1 = new test2();
        jf1.initTable();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_rankingMouseClicked

    private void aboutusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutusMouseClicked
        // TODO add your handling code here:
        AboutUs jf1 = new AboutUs();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_aboutusMouseClicked

    private void lpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpanelMouseClicked
        // TODO add your handling code here:
        LearningMode jf1 = new LearningMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_lpanelMouseClicked

    private void lpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpanelMouseEntered
        // TODO add your handling code here:
        learningmode.setBackground(Color.decode("#9370DB"));
    }//GEN-LAST:event_lpanelMouseEntered

    private void lpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lpanelMouseExited
        // TODO add your handling code here:
        learningmode.setBackground(Color.decode("#CCCCFF"));
    }//GEN-LAST:event_lpanelMouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        ExamMode jf1 = new ExamMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        exammode.setBackground(Color.decode("#EEE8AA"));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        exammode.setBackground(Color.decode("#FFFFCC"));
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        RankMode jf1 = new RankMode();
        jf1.show();
        dispose();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
        rankmode.setBackground(Color.decode("#DB7093"));
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        rankmode.setBackground(Color.decode("#FFCCCC"));
    }//GEN-LAST:event_jLabel3MouseExited
/**/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutpanel;
    private javax.swing.JLabel aboutus;
    private javax.swing.JPanel exammode;
    private javax.swing.JLabel iconmulti;
    private javax.swing.JLabel iconplus;
    private javax.swing.JLabel iconranking;
    private javax.swing.JLabel iconslash;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel learningmode;
    private javax.swing.JLabel lpanel;
    private javax.swing.JLabel music;
    private javax.swing.JPanel musicpanel;
    private javax.swing.JLabel ranking;
    private javax.swing.JPanel rankingpanel;
    private javax.swing.JPanel rankmode;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
