/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quickmathv2.Interface;

import java.awt.Color;
import javax.swing.ImageIcon;
import java.awt.Color;
import javax.swing.*;
import javax.sound.sampled.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import quickmathv2.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Lenovo
 */
public class test2 extends javax.swing.JFrame {
private Clip clip;
    /**
     * Creates new form Ranking
     */
    public test2() {
        initComponents();
        playMusic();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        searchBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lvl3 = new javax.swing.JLabel();
        lvl1 = new javax.swing.JLabel();
        lvl2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Back.setBackground(new java.awt.Color(255, 255, 255));
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BackMouseExited(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tekton Pro Ext", 0, 24)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/back white.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout BackLayout = new javax.swing.GroupLayout(Back);
        Back.setLayout(BackLayout);
        BackLayout.setHorizontalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackLayout.setVerticalGroup(
            BackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 26, 50, 50));

        jLabel3.setFont(new java.awt.Font("MV Boli", 0, 75)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RANKING");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 422, 100));

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));

        jLabel4.setFont(new java.awt.Font("Tekton Pro Ext", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 100, 90));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Tekton Pro Ext", 0, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 150, 90, 170));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 110, 80));

        jPanel5.setBackground(new java.awt.Color(153, 0, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 320, 620, 10));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("SimSun-ExtB", 3, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SEARCH :");
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 210, 50));

        jLabel9.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ALL");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 140, 40));

        jLabel10.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter");
        jLabel10.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel10FocusGained(evt);
            }
        });
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 180, 50));

        searchBox.setBackground(new java.awt.Color(255, 255, 255));
        searchBox.setFont(new java.awt.Font("SimSun-ExtB", 2, 48)); // NOI18N
        searchBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBoxMouseClicked(evt);
            }
        });
        searchBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBoxActionPerformed(evt);
            }
        });
        searchBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchBoxKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBoxKeyTyped(evt);
            }
        });
        getContentPane().add(searchBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 400, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/70-removebg-preview (1) (1).png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 40, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NO", "NAME", "LEVEL", "SCORE", "TIMETAKEN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 810, 250));

        lvl3.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lvl3.setForeground(new java.awt.Color(255, 255, 255));
        lvl3.setText("LEVEL 3");
        lvl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvl3MouseClicked(evt);
            }
        });
        getContentPane().add(lvl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 600, -1, -1));

        lvl1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lvl1.setForeground(new java.awt.Color(255, 255, 255));
        lvl1.setText("LEVEL 1");
        lvl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvl1MouseClicked(evt);
            }
        });
        getContentPane().add(lvl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, -1, -1));

        lvl2.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        lvl2.setForeground(new java.awt.Color(255, 255, 255));
        lvl2.setText("LEVEL 2");
        lvl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lvl2MouseClicked(evt);
            }
        });
        getContentPane().add(lvl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quickmathv2/MusicAndIcon/video.gif"))); // NOI18N
        jLabel1.setText("LEVEL 1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        jLabel11.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("LEVEL 1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LEVEL 1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 90, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 810, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseExited
        // TODO add your handling code here:
        Back.setBackground(Color.decode("#CCCCCC"));
    }//GEN-LAST:event_BackMouseExited

    private void BackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseEntered
        // TODO add your handling code here:
        Back.setBackground(Color.decode("#696969"));
    }//GEN-LAST:event_BackMouseEntered

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
        // TODO add your handling code here:
        MainPage jf1 = new MainPage();
        jf1.show();
        dispose();
        stopMusic();
    }//GEN-LAST:event_BackMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        MainPage jf1 = new MainPage();
        jf1.show();
        dispose();
        stopMusic();
        
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void lvl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl1MouseClicked
        // TODO add your handling code here:
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
        String sql= "select *  from ranking where lvl = '1'";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.sort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_lvl1MouseClicked

    private void lvl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl2MouseClicked
        // TODO add your handling code here:
        MusicPlayer player = MusicPlayer.getInstance();
        
        player.playbuttonMusic();
        String sql= "select *  from ranking where lvl = '2'";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.sort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_lvl2MouseClicked

    private void lvl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lvl3MouseClicked
        // TODO add your handling code here:
        MusicPlayer player = MusicPlayer.getInstance();
         
        player.playbuttonMusic();
        String sql= "select *  from ranking where lvl = '3'";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.sort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_lvl3MouseClicked

    private void searchBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBoxActionPerformed
        // TODO add your handling code here:
        String sql= "select *  from ranking";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.nameSort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_searchBoxActionPerformed

    private void searchBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBoxMouseClicked
        // TODO add your handling code here:
        searchBoxActionPerformed(null);
        
    }//GEN-LAST:event_searchBoxMouseClicked

    private void searchBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyTyped
        // TODO add your handling code here:
       searchBoxActionPerformed(null);
         
        
    }//GEN-LAST:event_searchBoxKeyTyped

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        String sql= "select *  from ranking";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        //Sorting sort =new Sorting();
       // sort.sort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        String sql= "select *  from ranking";
        String s= searchBox.getText();
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.nameSort(rank);
        int j=0;
        try{
            Searching bs = new Searching();
            
             j= bs.searchName(rank, s);
            if(j<0){
                System.out.println("dun hava");
            }
             else{
                System.out.println(rank.get(j));
              }
        }catch(Exception e){
            e.printStackTrace();
        }
        tbModel.setRowCount(0);
        int i=1;
        if(j>=0){
            String tcData[] ={String.valueOf(i),rank.get(j).getName(),rank.get(j).getLevel(),String.valueOf(rank.get(j).getScore()),rank.get(j).getTimeTaken()};
            tbModel.addRow(tcData);
        }
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void searchBoxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBoxKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            jLabel10.requestFocus();
        }
    }//GEN-LAST:event_searchBoxKeyPressed

    private void jLabel10FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel10FocusGained
        // TODO add your handling code here:
        String sql= "select *  from ranking";
        String s= searchBox.getText();
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.nameSort(rank);
        int j=0;
        try{
            Searching bs = new Searching();
            
             j= bs.searchName(rank, s);
            if(j<0){
                System.out.println("dun hava");
            }
             else{
                System.out.println(rank.get(j));
              }
        }catch(Exception e){
            e.printStackTrace();
        }
        tbModel.setRowCount(0);
        int i=1;
        if(j>=0){
            String tcData[] ={String.valueOf(i),rank.get(j).getName(),rank.get(j).getLevel(),String.valueOf(rank.get(j).getScore()),rank.get(j).getTimeTaken()};
            tbModel.addRow(tcData);
        }
    }//GEN-LAST:event_jLabel10FocusGained
private void playMusic() {
        try {
            // 加载音频文件
            InputStream audioFile = getClass().getResourceAsStream("/quickmathv2/MusicAndIcon/boom.wav");
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            clip = AudioSystem.getClip();
            clip.open(audioStream);
            clip.start(); // 开始播放
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException ex) {
            ex.printStackTrace();
        }
    }

private void stopMusic() {
        if (clip != null && clip.isRunning()) {
            clip.stop(); // 停止播放
            clip.close(); // 释放资源
        }
    }
public  void initTable(){
    String sql= "select *  from ranking";
        RankTable rt= new RankTable();
        ArrayList<Rankings> rank = new ArrayList<>();
        DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
        rank = rt.readRankings(sql);
        Sorting sort =new Sorting();
        sort.sort(rank);
        tbModel.setRowCount(0);
        int i=1;
        for (Rankings rankers : rank){
            System.out.println(rankers);
            String tcData[] ={String.valueOf(i),rankers.getName(),rankers.getLevel(),String.valueOf(rankers.getScore()),rankers.getTimeTaken()};
            i++;
            tbModel.addRow(tcData);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test2().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lvl1;
    private javax.swing.JLabel lvl2;
    private javax.swing.JLabel lvl3;
    private javax.swing.JTextField searchBox;
    // End of variables declaration//GEN-END:variables
}
